### PR TITLE
added shiny install since i got shiny not found error

### PR DESCRIPTION
**Pull request by amrrs**

### CODE REVIEW

**Review by petegordon — APPROVED** [review]

**Comment by petegordon** [comment]
Hey amrrs, after I accepted and then thought about it, I am not certain how it was not able to locate shiny; because the shiny library is installed in R-Portable-Win and R-Portable-Mac.  Are you running on Linux or something?  I am wondering what R was running when shiny was not available (i.e. previously installed)?  It needs to be a R out of either the -Win or -Mac directory; if it was then it might be an issue with .libPaths in the R environment.  Trying to track it down.  Let me know more details.  Thanks.

**Comment by amrrs** [comment]
Yes, I wondered the same after looking into the R Portable Folder. I was running it on a Mac.

**Comment by numpynewb** [comment]
I'm not sure this is the right place (for some reason I don't see how to report issues in the repo), but I am unable to get this to work. When I run `npm start` I just get a blank white screen. Is there something else I have to do apart from what is described in the README.md? Is there anything I can post here that would help people having this same problem? I have tried both on Mac and Windows.

**Comment by jazon33y** [comment]
Works for me on clean Windows install via Bootcamp. I suspect it has something to do with where it is looking for libraries.

**Comment by Cbuscollaboratory** [comment]
Give the standard electron-quick-starter project a try and get it working.

https://github.com/electron/electron-quick-start

If you experience the same problem then it is a NodeJS/electron issue and you might want to also record a video of the problem you’re experiencing... be sure to pay attention to the console output for any clues.  If you continue to have a problem open a new issue here.  Videos are nice with console messages.  You can also toggle the Chrome Dev Tools in the Eldctron window look for messages or errors on the console there also.


________________________________

**Comment by jazon33y** [comment]
Well for me It doesn't seem to be a node problem on Mac, but I could be wrong:

`stderr:Rscript execution error: No such file or directory`

When I print `execPath` in main.js, it is pointing to the correct absolute path for `Rscript`.

**Comment by Cbuscollaboratory** [comment]
Try running the Rscript execPath with the information from Main.js outside of electron; directly from terminal. 1) grab the path and command from debug printing. 2) be sure to check working directory that you are running from 3) try executing that command from the command line in terminal 4) if it doesn’t work, then continue to test navigating the directories from terminal to run  a simple ./Rscript -e “Version()” from terminal and ./R directly.

This is how how I tested the R-Portable-Mac directory when I first created it to make sure it was working (even when I had multiple versions of R installed in the Mac globally).  Factor out electron and just use the R and Rscript commands specific to R-Portable-Mac directory directly from terminal.

I have not tried it on a Mac that did not previously have R installed; if that’s the problem, let’s figure it out—because It’s supposed to work standalone.

Pete






________________________________

**Comment by jazon33y** [comment]
Thank you for your helpful advice. With it, I think I was able to identify the issue: 

```
/Users/jazon33y/Downloads/electron-quick-start/R-Portable-Mac/bin/Rscript --verbose -e 'shiny::runAppFile("/Users/jazon33y/Downloads/electron-quick-start/app.R", port=9191)'
running
  '/Library/Frameworks/R.framework/Versions/3.5/Resources/bin/R --slave --no-restore -e Version()'

Rscript execution error: No such file or directory
```

For some reason the Rscript is trying to use the system installed R,  version 3.5 (which maybe is the version you made the app with?). I don't have R 3.5 on my Mac, only 3.4, so it fails. But, this does indicate that on machines with no R at all, it will also fail.

**Comment by petegordon** [comment]
Hmm.  Yes, it is correct, the R-Portable-Mac directory has the 3.5 version of R in it.

I think the problem is that it is the execution of Rscript from the R-Portable-Mac directory somehow is not running the R script here... 

https://github.com/ColumbusCollaboratory/electron-quick-start/blob/master/R-Portable-Mac/bin/R

That is where the R_HOME_DIR is set.  Rather it is trying to run the Global R 3.5 version; and not finding it.  I will look into it this week and find an answer.  Give me a few days.  Thanks!

**Comment by petegordon** [comment]
I think; I've got the problem duplicated and understood.  But, I don't yet have a solution that works consistently.  I've been trying to use this suggestion to set R_LIB_SITES and PATH to get RScript to work but I get the blank screen when my global version of R is different than the R-Portable-Mac version.    I found the PATH and R_LIB_SITES suggested here...
https://stackoverflow.com/questions/35313704/rscript-launch-custom-r

image

Versus when I use the same version as my Global version of R....   (I am using RSwitch to switch between verisons of R on my Mac)

image

I pushed my changes; if anyone wants to take a look.  Still working on it; need some more time.  Thanks!

**Comment by petegordon** [comment]
I've pushed a fix.  Could use some help testing it.  I had to convert to using the R bash script on MacOS (instead of Rscript) and set a custom environment variable (NODE_R_HOME) to set the path to the R_Portable_Mac directory.  It seems to work for me; I can run different versions of R globally on my mac and it still runs the 3.5 in electron.  Although, I'm a little nervous about some of the sessionInfo ("unix default") which are apparently still pointing to dynamic libraries in /Library/Frameworks/R.Framework/3.5/   ....  Let me know if this works for you.  Thanks!

This screenshot shows me running R 3.1 with RSwitch globally; and electron working with 3.5 and the correct libPaths().  I used npm start to run it.

image

**Comment by jazon33y** [comment]
Thank you for working on this! I just pulled the new version and it works. I will go ahead and test it on a vanilla Mac OS install and report back here once that is finished (will need to reformat a drive so it might be a few hours).

**Comment by jonocarroll** [comment]
Thank you for the updates! I don't have R 3.5 on my Mac so I'll give it a test tomorrow and let you know how it goes.

**Comment by numpynewb** [comment]
I can confirm that this works on Mac now, albeit on a machine with R already installed. Will be interested to learn of the vanilla tests from @jazon33y 

If there is anything I can do to help move this along @petegordon, please do let me know. 

Also, is it feasible to get this working for linux too? Having the ability to publish an electron web-app powered by shiny would be quite something. If it were to end up being as simple as the current method, it would have huge impact for R devs looking to deploy their creations more widely and reliably. Currently, Shiny (R) users really only have two options for larger-scale deployment: RStudio buy-in or shinyproxy (which is not too easy to use, in my estimation).

**Comment by petegordon** [comment]
@jonocarroll @jazon33y @numpynewb Thanks for the testing and feedback!

@numpynewb if someone points me to a standalone directory of R working on Linux (i.e. Ubuntu) we could add it to electron super easy.  But, I haven't even begun to try a standalone Linux R directory--it might be easy--it might be painful--unknown.

I'd like to get the npm run package-[win/mac] commands to work better; they should ignore the R platforms that are not being packaged.

Thanks!
Pete

**Comment by jazon33y** [comment]
Ok, I can confirm that this works on a vanilla Mac OS install.

**Comment by ksasso** [comment]
@numpynewb It's possible you may have multiple Electron processes running. This is an issue we have been working to resolve. The fix should be straight forward. If you do an npm start and just see a blank screen try to launch task manager and close out any running electron processes and then re-launch.

**Comment by petegordon** [comment]
@numpynewb and @ksasso  the problem with processes running we've seen on windows; I don't think we've experienced it on macos as of yet.

All, I just updated the fork repo from the electron/electron-quick-start.  This pushed us to electron 2.0 and I made a few more changes to R bash file and added some more output to app.R (was testing the dynamic library references to make sure they are ok).

I think it is all good for macOS and Electron 2.0.  Let me know if you have any issues.  Thanks!

**Comment by jazon33y** [comment]
@petegordon @ksasso the new update looks good, and works too!

Also, may I suggest a new repo? Maybe named something like electronr ;) . It will allow for electronR-sepecific issues, and it would help give it the distinction and notoriety it truly deserves. 

Really, like @numpynewb, I believe this is a pretty huge deal and am super excited about it! Thank you both (and maybe others too?) for bringing this out into the open.

**Comment by jonocarroll** [comment]
Nearly there, I think. Still having some issues (the app _does_ show though, so definitely good progress):

It appears you're printing out the environment for debugging still

```
$ sed -n 42p main.js
console.log(process.env)
```

It appears that `~/.Rprofile` is still being sourced. e.g.

```
$ cat ~/.Rprofile
message("sourced .Rprofile")
```

results in 
```
$ npm start
<snip>
stdout:
R version 3.5.0 (2018-04-23) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> shiny::runApp(file.path('/Users/username/Sandbox/electron-quick-start/app.R'), port=9191)

stderr:sourced .Rprofile
Loading required package: shiny

Listening on http://127.0.0.1:9191
```

which is a problem if the user, for example, doesn't defensively load libraries for their general work but hasn't loaded them into the R-Portable instance, and just uses them namespaced in their startup script - this causes the entire app to crash, even if unrelated.

There also still seems to be some linking problems (though it does now work). The `Rscript` files still (try to) point to the installed version

```
$ ./R-Portable-Mac/bin/Rscript --verbose -e "1"
running
  '/Library/Frameworks/R.framework/Versions/3.5/Resources/bin/R --slave --no-restore -e 1'

Rscript execution error: No such file or directory
```

(identical for `./R-Portable-Mac/Rscript --verbose -e "1"`) and 

```
$ ./R-Portable-Mac/bin/R
/Users/username/Sandbox/electron-quick-start
*** R_HOME_DIR ***
/Users/username/Sandbox/electron-quick-start
./R-Portable-Mac/bin/R: line 258: /Users/username/Sandbox/electron-quick-start/etc/ldpaths: No such file or directory
```

which is referring to 

```
$ sed -n 258p ./R-Portable-Mac/bin/R
. "${R_HOME}/etc${R_ARCH}/ldpaths"
```

(need to point `R_HOME` to `NODE_R_HOME` or update that line?).

Happy to test again once you've had a look at these things. This will be extremely useful once it's running smoothly. Cheers!

**Pull request merged**
